apiVersion: v1
kind: Pod
metadata:
  name: "298311908301"
  namespace: default
  labels:
    priority: "2"
    servicesID: "298311908301"
spec:
  restartPolicy: OnFailure
  containers:
  - name: testenv
    image: yifan6185/testenv1:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      # Get a random CPU workload based on weight
      function get_weighted_random_cpu_load {
        # CPU usage distribution percentiles (CDF)
        cpu_loads=(0.015289306640625 0.01922607421875 0.022064208984375 0.025360107421875 0.031494140625 0.035064697265625 0.037994384765625 0.043487548828125 0.07818603515625 0.4482421875 0.7470703125)
        percentiles=(0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0)

        # Generate a random number between 0 and 1
        random=$(awk -v seed=$RANDOM 'BEGIN{srand(seed); print rand()}')
        # Find the corresponding CPU load based on the random number using interpolation
        for i in "${!percentiles[@]}"; do
          if (( $(echo "$random <= ${percentiles[$i]}" | bc -l) )); then
              if [ $i -eq 0 ]; then
                echo "${cpu_loads[0]}"
                return
              fi
              x0=${percentiles[$i-1]}
              x1=${percentiles[$i]}
              y0=${cpu_loads[$i-1]}
              y1=${cpu_loads[$i]}
              cpu_load=$(echo "scale=10; $y0 + ($random - $x0) * ($y1 - $y0) / ($x1 - $x0)" | bc -l)
              printf "%.15f\n" "$cpu_load"
              return
          fi
        done
      }

      # set total time and every running time
      total_time=487.2858345
      interval=30
      end_time=$(date -ud "$total_time seconds" +%s)

      # start workload
      while [[ $(date -u +%s) -le $end_time ]]; do
          current_time=$(date -u +%s)
          remaining_time=$((end_time - current_time))

          if ((remaining_time < interval)); then
              interval=$remaining_time
          fi

          cpu_load=$(get_weighted_random_cpu_load)
          echo "Applying CPU load: $cpu_load for $interval seconds"

          # calculate stress-ng parameters
          cpu_cores=$(echo "$cpu_load" | awk '{print int($1+1)}')
          load_per_core=$(echo "scale=0; ($cpu_load * 100) / $cpu_cores" | bc -l)

          stress-ng --cpu $cpu_cores --cpu-load $load_per_core --timeout $interval

          if ((remaining_time <= interval)); then
              break
          fi
      done
    resources:
      requests:
        cpu: "3.22265625"
        memory: "2262Mi"
      limits:
        cpu: "5.326171875"
        memory: "2262Mi"
